INSERT INTO taglie (nome, codice)
VALUES
    ('Extra Extra Small', 'XXS'),
    ('Extra Small', 'XS'),
    ('Small', 'S'),
    ('Medium', 'M'),
    ('Large', 'L'),
    ('Extra Large', 'XL'),
    ('Extra Extra Large', 'XXL'),
    ('3 Extra Large', 'XXXL'),
    ('4 Extra Large', '4XL'),
    ('5 Extra Large', '5XL'),
    ('Kids Extra Small', 'K-XS'),
    ('Kids Small', 'K-S'),
    ('Kids Medium', 'K-M'),
    ('Kids Large', 'K-L'),
    ('One Size', 'OS'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
    ('44', '44'),
    ('45', '45'),
    ('46', '46'),
    ('47', '47'),
    ('48', '48')
ON CONFLICT (codice) DO NOTHING;
